version: '3.8'
services:
  web:
    image: nginx:latest
    volumes:
      - ./docker/conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/var/www/html
    ports:
      - '9993:80'
    restart: unless-stopped
    depends_on:
      - php
  php:
    image: php:8-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./backend:/var/www/html
